services:
  postgres:
    image: postgres:16-alpine
    container_name: devboard-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d:ro

    networks:
      - devboard-net

  backend:
    build:
      context: ./backend
    container_name: devboard-backend

    environment:
      PORT: 8080
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable

    ports:
      - target: 8080
        published: ${BACKEND_PORT}
        protocol: TCP

    depends_on:
      - postgres

    networks:
      - devboard-net


  frontend:
    build:
      context: ./frontend
    container_name: devboard-frontend

    ports:
      - target: 4173
        published: ${FRONTEND_PORT}
        protocol: TCP
    
    depends_on:
      - backend

    networks:
      - devboard-net

networks:
  devboard-net:

volumes:
  postgres-data:

