FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o devboard-backend .

FROM alpine:3.20

WORKDIR /app

COPY --from=build /app/devboard-backend .

RUN chmod +x ./devboard-backend

EXPOSE 8080

CMD ["./devboard-backend"]
